module.exports = {
  $schema:
    "https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json",
  default: true, // 启用默认规则
  "ul-style": {
    style: "dash", // 使用破折号（-）作为无序列表的标记
  },
  "no-trailing-spaces": {
    br_spaces: 0, // 行末不允许有空格
    list_item_empty_lines: false, // 列表项之间不允许空行
  },
  "list-marker-space": false, // 列表标记后不要求有空格
  "line-length": false, // 行长度没有限制
  "no-inline-html": false, // 允许在 Markdown 中使用内联 HTML
  "no-duplicate-header": false, // 允许重复的标题
  "proper-names": {
    names: [
      // 定义了允许使用的专有名词
      "JavaScript",
      "HTML",
      "CSS",
      "AJAX",
      "JSON",
      "DOM",
      "BOM",
      "Less",
      "Sass",
      "SCSS",
      "HTTP",
      "HTTPS",
      "WebSocket",
      "ECMAScript",
      "ECMAScript 2015",
      "ECMAScript 6",
      "ES6",
      "ES2015",
      "jQuery",
      "jQuery Mobile",
      "React",
      "React Native",
      "Bootstrap",
      "Gulp",
      "Grunt",
      "webpack",
      "Yeoman",
      "npm",
      "spm",
      "Babel",
      "Mocha",
      "Jasmine",
      "PHP",
      "Java",
      "Node.js",
      "NodeJS",
      "MySQL",
      "MongoDB",
      "Redis",
      "Apache",
      "Nginx",
      "NGINX",
      "GitHub",
      "GitLab",
      "GitCafe",
      "Chrome",
      "Firefox",
      "Safari",
      "Internet Explore",
      "IE",
      "IE 7",
      "Opera",
      "UC",
      "Android",
      "iOS",
      "Windows",
      "OS X",
      "Ubuntu",
      "Linux",
      "Debian",
      "PC",
      "Mobile",
      "H5",
      "MacBook",
      "MacBook Pro",
      "MacBook Air",
      "iMac",
      "Mac Pro",
      "iPad",
      "Mac mini",
      "iPad Air",
      "iPad Air 2",
      "iPad mini",
      "iPhone",
      "iPhone 6s",
      "iPhone 6s Plus",
      "Apple Watch",
      "Alibaba",
      "Taobao",
      "Google",
      "Alphabet",
      "Apple",
      "Microsoft",
      "Yahoo",
      "FPS",
      "UI",
      "URL",
      "URI",
      "URLs",
      "URIs",
      "Visual Studio Code",
    ],
    code_blocks: false, // 在代码块中也不检查专有名词
  },
};
